language: objective-c
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - PAGER=cat
    - EDITOR=cat # for brew-file edit test
    - VISUAL=cat
  matrix:
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
before_install:
  - openssl aes-256-cbc -K $encrypted_43fa9741277b_key -iv $encrypted_43fa9741277b_iv -in .travis_rsa.enc -out .travis_rsa -d
  - cp .travis_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = bash ];then version="--bash";fi'
  #- brew update >& /dev/null && brew upgrade >& /dev/null # takes too much time... courses fail...
  - brewprefix=$(brew --prefix)
install:
  - '[ "$coveralls" = "coveralls-python" ] && sudo pip install coveralls >/dev/null || :'
  - '[ "$coveralls" = "python-coveralls" ] && sudo pip -e . --use-mirrors >/dev/null || :'
  - brew install rcmdnk/file/brew-file $version
  #- brew install vim --with-lua --HEAD # for option check test
  - brew install mobile-shell --with-check
  - brew info mobile-shell
  - brew install tig --HEAD --with-docs
  - brew install caskroom/cask/brew-cask
  - brew cask install firefox # for brew cask list test
  - brew tap homebrew/dupes # needed, as current travis environment is old and has some packages which are now under dupes, but travis environment doesn't have dupes tap.
  - cd ../
  - git clone git@github.com:rcmdnk/BrewfileTest
  - cd BrewfileTest
  - cp ../homebrew-file/BrewfileTest ./Brewfile
  - git commit -a -m "init" && git push -f || echo nothing to be done
  - cd ../homebrew-file
  - rm -rf ../BrewfileTest
before_script:
  - touch "$brewprefix/Library/Brewfile"
  - installed_brew=$(which brew-file)
  - exe=$(pwd)/bin/brew-file
  - git config --global push.default simple # to suppress git warning
script:
  #  - '[ "$version" != "" ] && diff $installed_brew $exe || :'
  #  - '[ "$version" != "" ] && brew file help | ( $exe help | diff /dev/fd/3 -) 3<&0 || :'
  #  - '[ "$version" != "" ] && brew file version | ( $exe version | diff /dev/fd/3 -) 3<&0 || :'
  #  - coverage run --parallel-mode $exe version
  #  - coverage run --parallel-mode $exe --version
  #  - coverage run --parallel-mode $exe help
  #  - coverage run --parallel-mode $exe || echo test
  #  - coverage run --parallel-mode $exe brew list >/dev/null
  #  - coverage run --parallel-mode $exe init -y -V 2
  #  - coverage run --parallel-mode $exe update -y -U -V 0
  #  - coverage run --parallel-mode $exe casklist -V 0
  #  - brew rm brew-cask
  #  - brew untap caskroom/cask
  #  - coverage run --parallel-mode $exe casklist -V 0
  #  - coverage run --parallel-mode $exe edit
  #  - coverage run --parallel-mode $exe set_repo -r git@github.com:rcmdnk/BrewfileTest -y -V 2
  #  - cp $brewprefix/Library/rcmdnk_BrewfileTest/Brewfile .
  #  - rm -rf $brewprefix/rcmdnk_BrewfileTest
  #  - coverage run --parallel-mode $exe install -U -V 2
  #  #- '[ "$TRAVIS_PULL_REQUEST" = "false" ] && coverage run --parallel-mode $exe update -y -U -V 0 || :'
  #  - coverage run --parallel-mode $exe update -y -U -V 0
  #  - export HOMEBREW_CASK_OPTS="--appdir=~/Applications --caskroom=/opt/homebrew-cask/Caskroom"
  #  - coverage run --parallel-mode $exe cask_upgrade -C -V 0
  #  - coverage run --parallel-mode $exe brew noinit list -V 0
  #  - coverage run --parallel-mode $exe clean
  #  - coverage run --parallel-mode $exe test -V 2
  #  - coverage run --parallel-mode $exe wrongcommand || echo test
  #  - cp Brewfile $brewprefix/Library/rcmdnk_BrewfileTest/Brewfile
  #  #- '[ "$TRAVIS_PULL_REQUEST" = "false" ] && coverage run --parallel-mode $exe push -V 0 || :'
  #  - coverage run --parallel-mode $exe push -V 0
  #  # Test with brew-wrap
  #  - source $(brew --prefix)/etc/brew-wrap
  #  - type brew
  #  - brew install hub -V 2
  #  - brew noinit install stow
  #  # Install test
  #  - brew rm brew-file
  #  - brew untap rcmdnk/file
  #  - rm -rf $brewprefix/bin/brew $brewprefix/Library $brewprefix/Cellar
  #  - rm -rf $brewprefix/.git*
  #  - curl -fsSL https://raw.github.com/rcmdnk/homebrew-file/install/install.sh |sh
  #  - rm -rf $brewprefix/bin/brew $brewprefix/Library $brewprefix/Cellar
  #  - rm -rf $brewprefix/.git*
  - coverage run --parallel-mode $exe help -V 0 >/dev/null
after_success:
  - coverage combine # should be done before removing brew-file
  - coveralls
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always

